# Getting Start Pytorch 
- python-based scientific computing package
- a replacement for numpy to use the power of GPUs
- DL research platform that provides maximum flexibility and speed

In [1]:
from __future__ import print_function
import torch

In [2]:
torch.__version__

'1.0.0'

## Tensors

In [3]:
# construct a 5x3 matrix, uninitalized
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 4.6566e-10, 0.0000e+00],
        [4.6566e-10, 8.4078e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0908e-05, 2.4449e-18, 7.7052e+31]])


In [4]:
# construct a randomly initalized matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.6794, 0.7495, 0.3362],
        [0.5719, 0.1994, 0.2155],
        [0.7198, 0.5830, 0.4231],
        [0.9857, 0.5113, 0.4561],
        [0.7251, 0.9794, 0.3721]])


In [5]:
# construct a matrix filed zeros and of dtype long 
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(type(x))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
<class 'torch.Tensor'>


In [6]:
# construct a tensor directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
# create a tensor based on an existing tensor
x = x.new_ones(5, 3, dtype=torch.double) # new_* : take in sizes
print(x)

x = torch.rand_like(x, dtype=torch.float) # override dtype, same size 
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.3671, 0.1766, 0.5552],
        [0.0731, 0.7689, 0.9500],
        [0.4514, 0.8843, 0.0620],
        [0.0889, 0.5142, 0.4425],
        [0.7023, 0.1747, 0.6895]])


In [8]:
print(x.size())

torch.Size([5, 3])


## Operations 

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2333, 0.9642, 1.3274],
        [0.2392, 1.0859, 1.9263],
        [0.9426, 1.4728, 0.9598],
        [0.4614, 1.0315, 0.9960],
        [1.2333, 0.9073, 1.0512]])


In [10]:
y

tensor([[0.8662, 0.7876, 0.7722],
        [0.1661, 0.3170, 0.9763],
        [0.4912, 0.5885, 0.8978],
        [0.3725, 0.5173, 0.5535],
        [0.5310, 0.7325, 0.3617]])

In [11]:
print(torch.add(x, y))

tensor([[1.2333, 0.9642, 1.3274],
        [0.2392, 1.0859, 1.9263],
        [0.9426, 1.4728, 0.9598],
        [0.4614, 1.0315, 0.9960],
        [1.2333, 0.9073, 1.0512]])


In [12]:
# providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.2333, 0.9642, 1.3274],
        [0.2392, 1.0859, 1.9263],
        [0.9426, 1.4728, 0.9598],
        [0.4614, 1.0315, 0.9960],
        [1.2333, 0.9073, 1.0512]])


In [13]:
# in-place
print(y)
y.add_(x)
print(y)

tensor([[0.8662, 0.7876, 0.7722],
        [0.1661, 0.3170, 0.9763],
        [0.4912, 0.5885, 0.8978],
        [0.3725, 0.5173, 0.5535],
        [0.5310, 0.7325, 0.3617]])
tensor([[1.2333, 0.9642, 1.3274],
        [0.2392, 1.0859, 1.9263],
        [0.9426, 1.4728, 0.9598],
        [0.4614, 1.0315, 0.9960],
        [1.2333, 0.9073, 1.0512]])


In [14]:
# Numpy-like indexing
print(x[:, 1])

tensor([0.1766, 0.7689, 0.8843, 0.5142, 0.1747])


In [15]:
print(x)

tensor([[0.3671, 0.1766, 0.5552],
        [0.0731, 0.7689, 0.9500],
        [0.4514, 0.8843, 0.0620],
        [0.0889, 0.5142, 0.4425],
        [0.7023, 0.1747, 0.6895]])


## Resizing/Reshape : torch.view 

In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
# if you have a one element tensor, use .item()
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.3795])
0.37946367263793945


## Numpy Bridge 

### Converting a torch tensor to a numpy array 

In [18]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [19]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy Array to Torch tensor 

In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
