# Autograd : Automatic differentiation 
- autograd: automatic differentiation for all operations on Tensors
- define-by-run framework

## Tensors 
- `.requires_grad = True`: it starts to track all operations 
- `.backward()`: all the gradients computed automatically
- `detach()`: prevent future computation from being tracked 

In [1]:
import torch

In [18]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [19]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [20]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [21]:
a = torch.rand(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## Gradients 

In [22]:
# out: single scalar (27.)
# out.backward() = out.backward(torch.tensor(1.))
out.backward()

In [23]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


## Jacobian product 

In [9]:
x = torch.rand(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ 96.3492, 678.6379, 778.7029], grad_fn=<MulBackward0>)


In [11]:
# 이제 y는 scalar값이 아님. so torch.autograd could not compute the full jacobain directly
# if we want the vector-jacobian product, pass the vector to backward as argument

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [12]:
# `with torch.no_grad()` : stop autograd on Tensors with .requires_grad=True
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
